steps:
  -name: 'gcr.io/cloud-builder/docker'
   args: ['build', '-t', 'gcr.io${_FIREBASE_PROJECT_ID}/firebase', './dockerfiles/firebase']
  -name: 'node:20.17.0'
   entrypoint: 'npm'
   args: ['install']
    